### ISSUE TITLE
Support 1.21.3

### ISSUE THREAD

**Issue by AfkF24** [endercrest/VoidSpawn#108]
**Describe the feature**
Title

**Additional context**
```
[15:34:56] [Server thread/INFO]: [VoidSpawn] Enabling VoidSpawn v1.21.0
[15:34:57] [Server thread/ERROR]: Error occurred while enabling VoidSpawn v1.21.0 (Is it up to date?)
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:188) ~[?:?]
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316) ~[?:?]
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274) ~[?:?]
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264) ~[?:?]
	at VoidSpawn-1.21.0.jar/com.endercrest.voidspawn.options.SoundOption.<clinit>(SoundOption.java:12) ~[VoidSpawn-1.21.0.jar:?]
	at VoidSpawn-1.21.0.jar/com.endercrest.voidspawn.modes.BaseMode.<init>(BaseMode.java:21) ~[VoidSpawn-1.21.0.jar:?]
	at VoidSpawn-1.21.0.jar/com.endercrest.voidspawn.modes.SpawnMode.<init>(SpawnMode.java:13) ~[VoidSpawn-1.21.0.jar:?]
	at VoidSpawn-1.21.0.jar/com.endercrest.voidspawn.ModeManager.setUp(ModeManager.java:28) ~[VoidSpawn-1.21.0.jar:?]
	at VoidSpawn-1.21.0.jar/com.endercrest.voidspawn.VoidSpawn.onEnable(VoidSpawn.java:35) ~[VoidSpawn-1.21.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[paper-1.21.3.jar]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[paper-1.21.3.jar]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:772) ~[paper-1.21.3.jar]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:534) ~[paper-1.21.3.jar]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[paper-1.21.3.jar]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1250) ~[paper-1.21.3.jar]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[paper-1.21.3.jar]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type interface org.bukkit.Sound; not a subtype of implementation type class java.lang.Enum
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:273) ~[?:?]
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:340) ~[?:?]
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:134) ~[?:?]
	... 20 more
[15:34:57] [Server thread/INFO]: [VoidSpawn] Disabling VoidSpawn v1.21.0
[15:34:57] [Server thread/INFO]: [VoidSpawn] v1.21.0 saving config
[15:34:57] [Server thread/INFO]: [VoidSpawn] v1.21.0 disabled
```

**Comment by GreenPxnda123** [comment]
1.21.4 same issue

**Comment by Kamycz3q** [comment]
1.21.3 problem here too

**Comment by ImBas** [comment]
Try my fork: https://github.com/ImBas/VoidSpawn/releases/tag/v1.21.3

**Comment by endercrest** [comment]
@ImBas If you are interested, I would love to merge your changes back into the main project. If so, please open a PR and I will happily merge it in.

**Comment by ImBas** [comment]
> [@ImBas](https://github.com/ImBas) If you are interested, I would love to merge your changes back into the main project. If so, please open a PR and I will happily merge it in.

Yeah of course, just opened a PR :)

**Comment by GreenPxnda123** [comment]
and 1.21.4

**Comment by ImBas** [comment]
> and 1.21.4

What is the error? Have you tried the 1.21.3 version to see if it works?
If not, post the error you're seeing

**Comment by endercrest** [comment]
This should now be fixed in https://github.com/endercrest/VoidSpawn/releases/tag/V1.22.0.
