### ISSUE TITLE
Could not pass event PlayerMoveEvent to VoidSpawn

### ISSUE THREAD

**Issue by PlayDatblockCom** [endercrest/VoidSpawn#44]
Plugin version: VoidSpawn version 1.17.0
Server version: Paper version git-Paper-221 (MC: 1.13.1)

This error is spamming in console/log.
```
[04:01:17 ERROR]: Could not pass event PlayerMoveEvent to VoidSpawn v1.17.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-221]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1034) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-221]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:936) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:834) ~[patched_1.13.1.jar:git-Paper-221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
```

**Comment by endercrest** [comment]
Closing, will reopen if a response is provided.

**Comment by Albert481** [comment]
Hi! I'm running VoidSpawn lastest, on 1.12.2.

I'm getting the same error. I do have a group with * permission, together with vs.override.

**Comment by endercrest** [comment]
@Albert481 Could you provide me with a full-stack track for this error?

**Comment by endercrest** [comment]
Closing this off till a full stacktrace is provided.
