### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by garsh1** [endercrest/VoidSpawn#69]
I am running 1.12.2 and my server is the same version. 

Whenever I log onto the server and I move, it spams the console with this:
[17:48:25 ERROR]: Could not pass event PlayerMoveEvent to VoidSpawn v1.18.3
java.lang.NoClassDefFoundError: org/bukkit/Tag
        at com.endercrest.voidspawn.MoveListener.isConflictingBlock(MoveListener.java:25) ~[?:?]
        at com.endercrest.voidspawn.MoveListener.onMoveEvent(MoveListener.java:19) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor102.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:711) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_241]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

And when I configure it to teleport me to spawn using the vs mode command and I jump in the void, it tells me this:  [VoidSpawn] Error while teleporting player: Mode has not been setup completely
[VoidSpawn] Details, World: spawn, Mode: Spawn and sends a similar message in chat.

**Comment by endercrest** [comment]
Hey, the latest versions of VoidSpawn only supports MC 1.13 and above. VoidSpawn v1.16.1 is the last supported version for MC 1.12 or below. You can download that at https://www.spigotmc.org/resources/voidspawn.19350/history.
