### ISSUE TITLE
Error Spam

### ISSUE THREAD

**Issue by Khosraw** [endercrest/VoidSpawn#79]
**Describe the bug**
When a player does anything like moving, breaking a block, running, or just standing, the plugin spams an error in the console and it fills up the entire console.

**To Reproduce**
1. Run VoidSpawn 1.19.1
2. Join the server
3. Check console for errors

**Expected behavior**
The console is just not supposed to be spamming those errors.

**VoidSpawn Version:** 1.19.1
**MC Version:** 1.8.9 (any version really)
**Spigot Version:** Paper version git-Paper-33d42c8e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) 

The error still happens on other MC versions like 1.15.2.

**Additional context**
`[18:48:18 WARN]: [VoidSpawn] Task #111 for VoidSpawn v1.19.1 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/Tag
        at com.endercrest.voidspawn.TouchTracker.isConflictingBlock(TouchTracker.java:20) ~[?:?]
        at com.endercrest.voidspawn.TouchTracker.run(TouchTracker.java:13) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[kSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:852) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:786) ~[kSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678) ~[kSpigot.jar:git-Paper-33d42c8e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]`

**Comment by endercrest** [comment]
Hey, this is caused due to your Spigot version being less than MC 1.13. As of VoidSpawn V1.17.0 and up, only version MC 1.13 and up are supported. 

I have just recently put a temporary incompatibility mode in V1.19.2 which might allow you to use it on MC 1.12.2. Please note that your version is still unsupported, but gives you a semi-fix.

You can download it from here: [V1.19.2](https://github.com/endercrest/VoidSpawn/releases/tag/V1.19.2)
