### ISSUE TITLE
Loading via Plugman causes exceptions to be thrown

### ISSUE THREAD

**Issue by cr0wm4n1** [endercrest/VoidSpawn#88]
**Describe the bug**
The plugin is causing the server to run at 350% cpu usage (the max) normal is around 40-60%. I get an error when starting the plugin.

**To Reproduce**
Not sure how to reproduce. 

**Expected behavior**

**Screenshots**
https://imgur.com/hbEZEQ4

1.19.3
1.17.1
Paper build #145

**Additional context**
Error when starting:

[08:52:33 INFO]: [VoidSpawn] Enabling VoidSpawn v1.19.3
[08:52:33 WARN]: Enabled plugin with unregistered PluginClassLoader VoidSpawn v1.19.3
[08:52:33 WARN]: javax.naming.NameAlreadyBoundException: A mode with the name spawn has already been set.
[08:52:33 WARN]:        at com.endercrest.voidspawn.ModeManager.addMode(ModeManager.java:77)
[08:52:33 WARN]:        at com.endercrest.voidspawn.ModeManager.setUp(ModeManager.java:28)
[08:52:33 WARN]:        at com.endercrest.voidspawn.VoidSpawn.onEnable(VoidSpawn.java:24)
[08:52:33 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:52:33 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[08:52:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[08:52:33 WARN]:        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:63)
[08:52:33 WARN]:        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127)
[08:52:33 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[08:52:33 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[08:52:33 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[08:52:33 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:830)
[08:52:33 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2170)
[08:52:33 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1981)
[08:52:33 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1962)
[08:52:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[08:52:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[08:52:33 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[08:52:33 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[08:52:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[08:52:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[08:52:33 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[08:52:33 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[08:52:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[08:52:33 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[08:52:33 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[08:52:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[08:52:33 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[08:52:33 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[08:52:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[08:52:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[08:52:33 INFO]: [VoidSpawn] v1.19.3 by EnderCrest enabled

**Comment by endercrest** [comment]
Hey, sorry for the delay in responding. Based on this, it looks like you are using PlugMan to load the plugin and are trying to enable it when it has already been enabled. Presently VoidSpawn doesn't support disabling and re-enabling. Could you provide more information about your use case that is causing this problem?
